# Generated by Django 3.1.4 on 2020-12-11 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('data_fabricacao', models.DateField(verbose_name='Data de Fabricacao')),
                ('quantidade_fabricada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('numero_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_lote', to='controle_vendas.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Ativo'), (2, 'Pendente'), (3, 'Concluido'), (4, 'Cancelado')], null=True, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='controle_vendas.cliente')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='controle_vendas.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendedor', to='controle_vendas.vendedor')),
            ],
        ),
    ]
