# Generated by Django 3.1.4 on 2020-12-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vendas', '0004_auto_20201211_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Concluido', 'Concluido'), ('Cancelado', 'Cancelado')], null=True, verbose_name='Status'),
        ),
    ]
