# Generated by Django 3.1.4 on 2020-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vendas', '0006_auto_20201211_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_compra',
            field=models.DateField(auto_now=True, verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='controle_vendas.Produto'),
        ),
    ]
